version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "09:00"
  open-pull-requests-limit: 10
  reviewers:
  - davemcorwin
  - amirbey
  assignees:
  - davemcorwin
  ignore:
  - dependency-name: newrelic
    versions:
    - 7.1.0
    - 7.1.1
    - 7.1.3
    - 7.2.0
    - 7.2.1
    - 7.3.0
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: aws-sdk
    versions:
    - 2.831.0
    - 2.834.0
    - 2.839.0
    - 2.843.0
    - 2.848.0
    - 2.852.0
    - 2.853.0
    - 2.854.0
    - 2.858.0
    - 2.863.0
    - 2.868.0
    - 2.874.0
    - 2.879.0
    - 2.884.0
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: bull
    versions:
    - 3.21.1
    - 3.22.0
  - dependency-name: mocha
    versions:
    - 8.3.1
  - dependency-name: chai
    versions:
    - 4.3.3
  - dependency-name: nock
    versions:
    - 13.0.6
    - 13.0.7
    - 13.0.8
